apps/home_page/urls.py
from django.urls import path

from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.home_page, name='home-page')
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLogInView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password/', views.PasswordEditView.as_view(), name='password-edit'),

    path('api/profiles/', views.ProfileAPIView.as_view())
]

website_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home_page.urls')),
    path('users/', include('apps.users.urls')),
    path('blog/', include('apps.blog.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.ImageField(default='images/profile/unknown_user.png', upload_to='profile/images')
    website_url = models.CharField(max_length=255, blank=True)
    facebook_url = models.CharField(max_length=255, blank=True)
    twitter_url = models.CharField(max_length=255, blank=True)
    instagram_url = models.CharField(max_length=255, blank=True)
    pinterest_url = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self):
        super().save()

        img = Image.open(self.user_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.user_image.path)

apps/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import forms, UserCreationForm

from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserEditForm(forms.ModelForm):
    email = forms.EmailInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileEditForm(forms.ModelForm):
    email = forms.EmailInput()

    class Meta:
        model = Profile
        fields = ['user_image', 'website_url', 'facebook_url', 'twitter_url', 'instagram_url', 'pinterest_url']

apps/users/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response

from .forms import UserRegisterForm, UserEditForm, ProfileEditForm
from .models import Profile
from .serializer import ProfileSerializer


class UserRegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')


class UserLogInView(LoginView):
    template_name = 'users/login.html'


@login_required()
def profile(request):
    if request.method == 'POST':
        u_form = UserEditForm(request.POST, instance=request.user)
        p_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserEditForm(instance=request.user)
        p_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'users/profile_edit.html', context)


class PasswordEditView(PasswordChangeView):
    template_name = 'users/password_edit.html'
    success_url = reverse_lazy('login')


class ProfileAPIView(APIView):
    def get(self, request):
        queryset = Profile.objects.all()
        serializer_class = ProfileSerializer(queryset, many=True)
        return Response(serializer_class.data)

apps/users/templates/users/login.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">Login form</h3>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Login</button>
                        <a class="btn btn-outline-secondary" href="{% url 'home_page:home-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/password_edit.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Password{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">Change password form</h3>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Update</button>
                        <a class="btn btn-outline-secondary" href="{% url 'home_page:home-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/profile_edit.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">Edit profile form</h3>
                <hr>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                    <p class="text-muted">Do you want to change your password?
                        <a href="{% url 'users:password-edit' %}">Click here</a>
                    </p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Update</button>
                        <a class="btn btn-outline-secondary" href="{% url 'home_page:home-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/register.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Register{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">User registration form</h3>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Register</button>
                        <a class="btn btn-outline-secondary" href="{% url 'home_page:home-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}