apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogPageView.as_view(), name='blog-page'),

    path('post/add/', views.AddPostView.as_view(), name='add-post'),
    path('post/<int:pk>/details/', views.PostDetailView.as_view(), name='post-details'),
    path('post/<int:pk>/update/', views.UpdatePostView.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', views.DeletePostView.as_view(), name='delete-post'),
    path('post/<int:pk>/like/', views.PostLikeToggleView.as_view(), name='post-like'),
    path('post/<int:pk>/dislike/', views.PostDislikeToggleView.as_view(), name='post-dislike'),

    path('category/add/', views.AddCategoryView.as_view(), name='add-category'),
    path('category/<str:category>/details/', views.CategoryListView.as_view(), name='category-details'),

    path('api/posts/', views.PostAPIView.as_view())
]

website_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home_page.urls')),
    path('users/', include('apps.users.urls')),
    path('blog/', include('apps.blog.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
from PIL import Image


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('blog:blog-page')


class Post(models.Model):
    title = models.CharField(max_length=255)
    post_image = models.ImageField(blank=True, null=True, upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    # body = models.TextField()
    add_post_date = models.DateTimeField(auto_now_add=True)
    change_post_date = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    likes = models.ManyToManyField(User, related_name='post_likes')
    dislikes = models.ManyToManyField(User, related_name='post_dislikes')
    like_updated_at = models.DateTimeField(auto_now=timezone.now())

    def __str__(self):
        return self.title

    @staticmethod
    def get_absolute_url():
        return reverse('blog:blog-page')

    def sum_likes(self):
        return self.likes.count()

    def sum_dislikes(self):
        return self.dislikes.count()

    def save(self):
        super().save()

        img = Image.open(self.post_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.post_image.path)

apps/blog/forms.py
from django import forms

from .models import Post, Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'New Category',
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'body', 'post_image']
        labels = {
            'title': 'Post Title',
            'category': 'Choose Category',
            'body': 'Post Text',
        }


class EditPostForm(PostForm):
    PostForm.Meta.labels = {
        'title': 'Edit Post Title',
        'category': 'Edit Post Category',
        'body': 'Edit Post Text',
        'post_image': 'Change Post Image',
    }

apps/blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Post, Category
from .forms import CategoryForm, PostForm, EditPostForm
from .serializer import PostSerializer


class BlogPageView(ListView):
    model = Post
    template_name = 'blog/main_page.html'
    ordering = ['-id']


class AddPostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_details.html'


class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/update_post.html'
    form_class = EditPostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse('blog:post-details', kwargs={'pk': self.object.pk})


class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:blog-page')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostLikeToggleView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs['pk'])
        post_qs = Post.objects.filter(id=kwargs['pk'])
        user = self.request.user
        if self.request.user.is_authenticated:
            if all([user not in post.likes.all(), user not in post.dislikes.all()]):
                post.likes.add(user)
                post_qs.update(like_updated_at=timezone.now())
                return reverse('blog:post-details', kwargs={'pk': kwargs['pk']})
            elif user in post.likes.all():
                post.likes.remove(user)
            elif user in post.dislikes.all():
                post.dislikes.remove(user)
                post.likes.add(user)
                post_qs.update(like_updated_at=timezone.now())
            else:
                post.likes.add(user)
                post_qs.update(like_updated_at=timezone.now())
            return reverse('blog:post-details', kwargs={'pk': kwargs['pk']})


class PostDislikeToggleView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs['pk'])
        post_qs = Post.objects.filter(id=kwargs['pk'])
        user = self.request.user
        if self.request.user.is_authenticated:
            if all([user not in post.likes.all(), user not in post.dislikes.all()]):
                post.dislikes.add(user)
                post_qs.update(like_updated_at=timezone.now())
                return reverse('blog:post-details', kwargs={'pk': kwargs['pk']})
            elif user in post.likes.all():
                post.likes.remove(user)
                post.dislikes.add(user)
                post_qs.update(like_updated_at=timezone.now())
            elif user in post.dislikes.all():
                post.dislikes.remove(user)
            else:
                post.dislikes.add(user)
                post_qs.update(like_updated_at=timezone.now())
            return reverse('blog:post-details', kwargs={'pk': kwargs['pk']})


class AddCategoryView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'blog/add_category.html'


class CategoryListView(ListView):
    model = Post
    template_name = 'blog/category_details.html'

    def get_queryset(self):
        category = get_object_or_404(Category, name=self.kwargs.get('category').capitalize().replace('-', ' '))
        return Post.objects.filter(category=category).order_by('-add_post_date')


class PostAPIView(APIView):
    def get(self, request):
        queryset = Post.objects.all()
        serializer_class = PostSerializer(queryset, many=True)
        return Response(serializer_class.data)

apps/blog/templates/blog/add_category.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Post{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">New post form</h3>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Add</button>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:blog-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/add_post.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Post{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">Add post form</h3>
                <hr>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Post</button>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:blog-page' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/category_details.html
{% extends 'home_page/base.html' %}

{% block title %}Category Details{% endblock title %}

{% block content %}
<h1 class="text-center my-4">Posts by category "{{ view.kwargs.category|title }}"</h1>
<div class="container-fluid">
    {% for post in object_list %}
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="form-control">
                <h4><a href="{% url 'blog:post-details' post.pk %}">{{ post.title|title }}</a></h4>
                Author - {{ post.author }}. Category - <a
                    href="{% url 'blog:category-details' post.category.name|lower|slugify %}">{{ post.category }}</a>.
                <p class="article-content">{{ post.body|safe|truncatewords:50 }}</p>
                <small class="text-muted">Added - {{ post.add_post_date }}</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

apps/blog/templates/blog/delete_post.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete Post{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <form method="POST">
                    <h3 class="text-center mb-3">Are you sure want to delete Post - "{{ post.title }}"?</h3>
                    {% csrf_token %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a class="btn btn-outline-secondary" href="{% url 'blog:post-details' object.id %}">Cancel</a>
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/main_page.html
{% extends 'home_page/base.html' %}

{% block title %}Blog Page{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h1 class="text-center mt-4">Posts list</h1>
    <div class="container-fluid">
        {% for post in object_list %}
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="form-control">
                        <h4>
                            {% if post.post_image %}
                                <img class="rounded-circle account-img" src="{{ post.post_image.url }}" alt="Post image">
                            {% endif %}
                            <a href="{% url 'blog:post-details' post.pk %}">{{ post.title|title }}</a>
                        </h4>
                        Author - {{ post.author }}. Category - <a href="{% url 'blog:category-details' post.category.name|lower|slugify %}">{{ post.category }}</a>.
                        <p class="article-content">{{ post.body|safe|truncatewords:50 }}</p>
                        <small class="text-muted">Added - {{ post.add_post_date }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/post_detail.html
{% extends 'home_page/base.html' %}

{% block title %}Post Details{% endblock title %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center border-bottom mb-3">Post Detail</h3>
                <p>Title:
                    <span class="form-control">{{ post.title }}</span>
                </p>
                <p>Author:
                    <span class="form-control">{{ post.author }}</span>
                </p>
                <p>Category:
                    <span class="form-control">{{ post.category }}</span>
                </p>
                <p>Post text:
                    <span class="form-control">{{ post.body }}</span>
                </p>
                <p>Last changing:
                    <span class="form-control">{{ post.change_post_date }}</span>
                </p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'blog:blog-page' %}" class="btn btn-outline-secondary">Back</a>
                    <a href="{% url 'blog:update-post' post.pk %}" class="btn btn-outline-secondary">Update Post</a>
                    <a href="{% url 'blog:delete-post' object.id %}" class="btn btn-outline-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/post_details.html
{% extends 'home_page/base.html' %}

{% block title %}Post Details{% endblock title %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center border-bottom mb-3">Post Detail</h3>
                <p>Title:
                    <span class="form-control">{{ post.title }}</span>
                </p>
                <p>Author:
                    <span class="form-control">{{ post.author }}</span>
                </p>
                <p>Category:
                    <span class="form-control">{{ post.category }}</span>
                </p>
                <p>Post text:
                <dir class="form-control">
                    <span>{{ post.body|safe }}</span>
                </dir>
                </p>
                <p>Post image:
                <dir class="form-control">
                    <img class="rounded-circle account-img" src="{{ post.post_image.url }}" alt="Post image">
                </dir>
                </p>
                <p>Last changing:
                    <span class="form-control">{{ post.change_post_date }}</span>
                </p>
                <hr class="mt-4">
                <div class="row">
                    <div class="col-4">
                        <form class="d-inline-block" method="POST" action="{% url 'blog:post-like' object.id %}">
                            {% csrf_token %}
                            {% if request.user in post.likes.all %}
                            <button class="btn btn-outline-secondary active" type="submit">
                                <span class="fas fa-thumbs-up"></span>
                            </button>
                            {% else %}
                            <button class="btn btn-outline-secondary" type="submit">
                                <span class="fas fa-thumbs-up"></span>
                            </button>
                            {% endif %}
                            {{ post.sum_likes }}
                        </form>
                        <form class="d-inline-block" method="POST" action="{% url 'blog:post-dislike' post.id %}">
                            {% csrf_token %}
                            {% if request.user in post.dislikes.all %}
                            <button class="btn btn-outline-secondary active" type="submit">
                                <span class="fas fa-thumbs-down"></span>
                            </button>
                            {% else %}
                            <button class="btn btn-outline-secondary" type="submit">
                                <span class="fas fa-thumbs-down"></span>
                            </button>
                            {% endif %}
                            {{ post.sum_dislikes }}
                        </form>
                    </div>
                    <div class="col-8 d-flex justify-content-end">
                        <a href="{% url 'blog:blog-page' %}" class="btn btn-outline-secondary">Back</a>
                        {% if object.author == user %}
                        <a href="{% url 'blog:update-post' post.pk %}" class="btn btn-outline-secondary">Update</a>
                        <a href="{% url 'blog:delete-post' object.id %}" class="btn btn-outline-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/blog/templates/blog/update_post.html
{% extends 'home_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Post{% endblock title%}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <div class="form-control">
                <h3 class="text-center">Update post form</h3>
                <hr>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy|safe }}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-outline-secondary" type="submit">Update</button>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:post-details' object.id %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}