apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogPageView.as_view(), name='blog-page'),

    path('post/add/', views.AddPostView.as_view(), name='add-post'),
    path('post/<int:pk>/details/', views.PostDetailView.as_view(), name='post-details'),
    path('post/<int:pk>/update/', views.UpdatePostView.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', views.DeletePostView.as_view(), name='delete-post'),
    path('post/<int:pk>/like/', views.PostLikeToggleView.as_view(), name='post-like'),
    path('post/<int:pk>/dislike/', views.PostDislikeToggleView.as_view(), name='post-dislike'),

    path('category/add/', views.AddCategoryView.as_view(), name='add-category'),
    path('category/<str:category>/details/', views.CategoryListView.as_view(), name='category-details'),

    path('api/posts/', views.PostAPIView.as_view())
]

apps/home_page/urls.py
from django.urls import path

from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.home_page, name='home-page')
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLogInView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password/', views.PasswordEditView.as_view(), name='password-edit'),

    path('api/profiles/', views.ProfileAPIView.as_view())
]

website_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home_page.urls')),
    path('users/', include('apps.users.urls')),
    path('blog/', include('apps.blog.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home_page/models.py
from django.db import models

# Create your models here.

apps/home_page/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, 'home_page/home_page.html', {'content': 'Home page'})

apps/home_page/templates/home_page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}

    {% block meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}

    {% block style %}
        <link rel="stylesheet" type="text/css" href="{% static 'home_page/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fontawesome_free/css/all.min.css' %}">
    {% endblock style %}

    <title>{% block title %}{% endblock title%}</title>
{% endblock head %}
</head>
{% block body %}
<body class="{% block bodyclass %}{% endblock %}">

    <div class="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home_page:home-page' %}">
                                <span class="fas fa-home"></span>&nbsp;Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog-page' %}">
                                <span class="fab fa-blogger"></span>&nbsp;Blog
                            </a>
                        </li>
                        {% if user.is_authenticated and 'blog' in request.path %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for category in category_data %}
                                <li>
                                    <a class="dropdown-item"
                                       href="{% url 'blog:category-details' category.name|lower|slugify %}">
                                        {{ category.name }}
                                    </a>
                                </li>
                                {% endfor %}
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'blog:add-category' %}">
                                    Add a new Category</a></li>
                            </ul>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:add-post' %}">
                                <span class="fas fa-plus"></span>&nbsp;Add Post
                            </a>
                        </li>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex ms-4">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'users:login' %}">
                                    <span class="fas fa-sign-in-alt"></span>&nbsp;Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">
                                    <span class="fas fa-user-plus"></span>&nbsp;Register
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:profile' %}">
                                    <span class="fas fa-user-edit"></span>&nbsp;Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">
                                    <span class="fas fa-sign-out-alt"></span>&nbsp;Logout
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}{% endblock content %}

    {% block script %}
        <script src="{% static 'home_page/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    {% endblock script %}

</body>
{% endblock body %}
</html>

apps/home_page/templates/home_page/home_page.html
{% extends 'home_page/base.html' %}

{% block title %}Home Page{% endblock title%}

{% block content %}
<h1>{{ content }}</h1>
{% endblock content %}